### ISSUE TITLE
weird gap in server list

### ISSUE THREAD

**Issue by TPO100Cofficial** [XYZenix/DTM-08#1]
![image](https://user-images.githubusercontent.com/33667869/117367746-1aaeb100-aeb2-11eb-8c60-4f00c248c42a.png)
being on linux, which doesn't use the native discord title bar might contribute to this

**Comment by XYZenix** [comment]
should be fixed [(21w18b)](https://github.com/XYZenix/XYZenixThemes/commit/af0f34f0a92042fb9f5cea7e91379ae1de7af426)
