### ISSUE TITLE
hi please roll back the new upload modal changes

### ISSUE THREAD

**Issue by TPO100Cofficial** [XYZenix/DTM-08#10]
![image](https://user-images.githubusercontent.com/33667869/136121551-7b33c89f-b2a4-431e-a1ef-7157a8bfe98b.png)
hi please roll back the new upload modal changes this is Really Really hard to read and i get that discord used to have a blurple upload modal but they changed it for a reason
"just do your own custom css to get rid of it" that does not work i have !important on every line of my patch for dtm-08 that relates to this modal and it does not work (did you use !important yourself? if so was that an accident?)

**Comment by XYZenix** [comment]
yes i used `!important` in some places but not for the backgrounds so you could change them but i changed it anyway, is the new one ok?
![image](https://user-images.githubusercontent.com/51988432/136122574-3d597b4c-edb5-4901-974e-d8b968f00ff9.png)

**Comment by TPO100Cofficial** [comment]
ok thank you!
maybe i was just doing something wrong myself? i could swear i was selecting the right element but it still wouldn't budge
