### ISSUE TITLE
strange blue chunks and missing thread icon in the message menu

### ISSUE THREAD

**Issue by TexNat** [XYZenix/DTM-08#11]
![image](https://user-images.githubusercontent.com/64905176/146516092-bdcea674-4c64-415c-8d20-adfed5dddc29.png)
![image](https://user-images.githubusercontent.com/64905176/146516292-fb7f38ec-2d65-456c-b807-8fec8e168519.png)
i can only assume this was caused by an update or something? i have no other themes and turning off all my plugins doesn't fix it either

**Comment by XYZenix** [comment]
the blue parts are intentional, i tried making the icons not look completely flat and this is the best i could come up with

as for the missing thread icon, should be fixed now
