### ISSUE TITLE
light theme top bar layout is broken? + sorry about last two issues, those were different htemes messing dtm-08 up

### ISSUE THREAD

**Issue by TPO100Cofficial** [XYZenix/DTM-08#5]
![image](https://user-images.githubusercontent.com/33667869/117501594-c963f780-af6d-11eb-80fb-5e89e4adf728.png)
![image](https://user-images.githubusercontent.com/33667869/117501657-df71b800-af6d-11eb-9be1-90dffe65bb4e.png)

**Comment by TPO100Cofficial** [comment]
nope. even checked disabling themerepo since that seemed to contribute because banners n such, but still has this weird border.
judging by the colours, it could maybe be a "forgetting to hide title bar for light theme on linux" thing?? maybe???
though, considering
> i don't have this problem,
probably not that, couldn't be an outdated version because auto-update too
it could be discord experiments, now that i think of it, but i don't know

![image](https://user-images.githubusercontent.com/33667869/117504463-fd411c00-af71-11eb-9225-cbe1f4d2b11a.png)
diving into css, it seems to be a weird misplaced margin? can easily fix this with some very primitive custom css, though
think it's just a me issue, though if anyone else gets this i'll post the custom css here:

```
.theme-light .content-98HsJk {
    margin-top: 0px;
}
```

**Comment by XYZenix** [comment]
oh yeah i see the problem idk what that line of css was doing there anyway, im removing it next time i update dtm-08
