### ISSUE TITLE
member list's user popup is a bit broken

### ISSUE THREAD

**Issue by TPO100Cofficial** [XYZenix/DTM-08#6]
![image](https://user-images.githubusercontent.com/33667869/117645955-b96d3300-b17a-11eb-89d7-d1e42ec431a3.png)

**Comment by XYZenix** [comment]
1. the remove button freezing on click for integration roles is from discord itself and the add button isn't there... are you using web discord? if so, what browser?

**Comment by TPO100Cofficial** [comment]
> the remove button freezing on click for integration roles is from discord itself and the add button isn't there...
what? sorry just confused
> are you using web discord
no?????

**Comment by XYZenix** [comment]
if you were referring to the close button staying visible when clicked on an integration role (that cannot be removed from bots, etc.) it's like that for me without the theme so i don't think it's because of the theme

as for the add button, once again, see if you have any other themes enabled

**Comment by TPO100Cofficial** [comment]
as for the roles,
ohhh yeah, i forgot that
as for the add button, nope
i even tried removing literally everything else, but no luck

**Comment by XYZenix** [comment]
> i even tried removing literally everything else, but no luck
even custom css? because i tried both canary and stable, i don't have this problem so idk how to fix it

**Comment by TPO100Cofficial** [comment]
..nevermind, apparently the problem fixed itself? guess discord was just being weird
