### ISSUE TITLE
(plugin compatibility issue) after going into a pinned dm (PinDMs) and going back to a server, the home button becomes round

### ISSUE THREAD

**Issue by TPO100Cofficial** [XYZenix/DTM-08#7]
![image](https://user-images.githubusercontent.com/33667869/118274134-49311b00-b4b4-11eb-97b5-a5e2ce98b072.png)

also, the home button doesn't want to turn off.
![image](https://user-images.githubusercontent.com/33667869/118274652-ed1ac680-b4b4-11eb-89d7-6501efb8a2dc.png)

**Comment by XYZenix** [comment]
are you using any bd/pc plugins? if so, which ones?

**Comment by XYZenix** [comment]
oh, PinDMs. i tried that plugin and there's no problems with DTM-08 compatibility as far as i can tell, is there any other plugins you're using that could be causing this?

**Comment by TPO100Cofficial** [comment]
sorry, forgot about this
i disabled everything and it seems to work
i have no clue what could even cause this

edit before even posting: oh, apparently it was TypingIndicator!

**Comment by XYZenix** [comment]
i dont think it was the plugin causing it but i did fix an issue that looks like it could be related. i don't use the plugin in question and i can't reproduce the bug when i tried using the plugin. so if you can check and see if it's fixed, that'd be nice
