### ISSUE TITLE
Reply thing isn't working.

### ISSUE THREAD

**Issue by A983Hub** [XYZenix/DTM-08#8]
When i'm using DTM-08, the reply thing where you can choose to ping or not ping or to not reply is not visible, while on normal discord theme and on other themes, it does show up.

For example.
![bandicam 2021-06-05 07-15-05-624](https://user-images.githubusercontent.com/69992569/120892945-d6582300-c5cd-11eb-8871-183fc95ed3db.jpg)

Now, here is how it looks like in DTM-08.
![bandicam 2021-06-05 07-15-21-038](https://user-images.githubusercontent.com/69992569/120892952-e1ab4e80-c5cd-11eb-92ee-06ede8da47c9.jpg)

It's literally invisible. Can't turn pinging on or off, or to not reply. I just have to reply anyways if i want to or not. No going back.

Proof that i was trying to reply.
![bandicam 2021-06-05 07-15-24-836](https://user-images.githubusercontent.com/69992569/120892969-fa1b6900-c5cd-11eb-82d2-000908a230fd.jpg)

If you guys are gonna fix this issue, that's great.

**Comment by XYZenix** [comment]
should be fixed on both dtm-08 and dtm-16

**Comment by a8underscore** [comment]
![image](https://user-images.githubusercontent.com/60801647/125813476-bad7493b-53ec-4468-9b21-60ea3fba6711.png)
now that this is a released feture, it works fine
we can close this issue?

**Comment by XYZenix** [comment]
it wasnt fixed, now it is, closing this

also, it was referring to this:
![image](https://user-images.githubusercontent.com/51988432/125818527-679f8065-a35b-4d80-b783-09792d76a7f6.png)
